[shell]
program = 'C:\Windows\System32\wsl.exe'
args = ["--cd ~"]

[env]
TERM = "xterm-256color"

[font]
normal.family = "Hack Nerd Font"
size = 13

[window]
padding.x = 5
opacity = 0.85
blur = true

[colors.cursor]
cursor = "#f7f7f7"
