[shell]
program = 'C:\Windows\System32\wsl.exe -d Arch'
args = ["--cd ~"]

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMonoNL Nerd Font"
size = 13

[window]
padding.x = 5
opacity = 0.85
blur = true

[colors.primary]
background = "#181616"
foreground = "#dcd7ba"

[colors.cursor]
cursor = "#c8c093"
text = "#c8c093"

[colors.selection]
background = "#2d4f67"
text = "#c8c093"

[colors.normal]
black = "#090618"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
magenta = "#957fb8"
cyan = "#6a9589"
white = "#c8c093"

[colors.bright]
black = "#727169"
red = "#e82424"
green = "#98bb6c"
yellow = "#e6c384"
blue = "#7fb4ca"
magenta = "#938aa9"
cyan = "#7aa89f"
white = "#dcd7ba"

[[colors.indexed_colors]]
index = 16
color = "#ffa066"

[[colors.indexed_colors]]
index = 17
color = "#ff5d62"
